import { Ionicons } from '@expo/vector-icons';
import React, { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { AppButton } from './AppButton';
import { Card } from './Card';
import { DataFreshnessBadge } from './DataFreshnessBadge';
import { SectionHeader } from './SectionHeader';
import {
  decideAdvice,
  generateAdvice,
  getAdviceDecisions,
  restoreAdvice,
  type AdviceDecision,
  type TripAdvice,
} from '../services/adviceService';
import { colors, spacing } from '../theme';
import type { SavedTrip, WeatherCondition } from '../types';

/**
 * Rule-based recommendations for the active trip. Accepting applies a
 * small local effect (packing item, timeline reminder); dismissing hides
 * the advice but it can always be restored.
 */
export function AdviceCard({
  trip,
  weather,
  transportOptionCount,
  onAccept,
}: {
  trip: SavedTrip;
  weather?: WeatherCondition;
  transportOptionCount: number;
  onAccept: (advice: TripAdvice) => Promise<void> | void;
}) {
  const [decisions, setDecisions] = useState<Record<string, AdviceDecision>>({});
  const [showDismissed, setShowDismissed] = useState(false);

  useEffect(() => {
    getAdviceDecisions().then(setDecisions);
  }, [trip.id]);

  const advice = useMemo(
    () => generateAdvice(trip, { weather, transportOptionCount }),
    [trip, weather, transportOptionCount],
  );
  const active = advice.filter((a) => !decisions[a.id]);
  const dismissed = advice.filter((a) => decisions[a.id] === 'dismissed');

  if (advice.length === 0) return null;

  const accept = async (a: TripAdvice) => {
    await onAccept(a);
    setDecisions(await decideAdvice(a.id, 'accepted'));
  };
  const dismiss = async (a: TripAdvice) => setDecisions(await decideAdvice(a.id, 'dismissed'));
  const restore = async (a: TripAdvice) => setDecisions(await restoreAdvice(a.id));

  return (
    <Card>
      <SectionHeader
        title="Recommendations"
        subtitle="Generated by simple rules from your trip details — not AI"
      />
      <DataFreshnessBadge mode="estimate" provider="A2Z rules" />
      {active.length === 0 && (
        <Text style={styles.empty}>Nothing to flag right now — you have handled everything.</Text>
      )}
      {active.map((a) => (
        <View key={a.id} style={styles.row}>
          <Text style={styles.title}>{a.title}</Text>
          <Text style={styles.body}>{a.recommendation}</Text>
          <Text style={styles.reason}>Why: {a.reason}</Text>
          <View style={styles.actions}>
            <AppButton label={a.acceptLabel} icon="checkmark" small onPress={() => accept(a)} />
            <AppButton label="Dismiss" variant="ghost" small onPress={() => dismiss(a)} />
          </View>
        </View>
      ))}
      {dismissed.length > 0 && (
        <Pressable
          onPress={() => setShowDismissed((v) => !v)}
          style={styles.dismissedToggle}
          accessibilityRole="button"
        >
          <Text style={styles.dismissedToggleText}>
            Dismissed ({dismissed.length}) {showDismissed ? '— hide' : '— show'}
          </Text>
          <Ionicons name={showDismissed ? 'chevron-up' : 'chevron-down'} size={14} color={colors.textMuted} />
        </Pressable>
      )}
      {showDismissed &&
        dismissed.map((a) => (
          <View key={a.id} style={[styles.row, styles.rowDismissed]}>
            <Text style={styles.titleDismissed}>{a.title}</Text>
            <AppButton label="Restore" variant="ghost" small onPress={() => restore(a)} />
          </View>
        ))}
    </Card>
  );
}

const styles = StyleSheet.create({
  empty: { fontSize: 13, color: colors.textMuted, marginTop: spacing.sm },
  row: {
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: 3,
  },
  rowDismissed: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  title: { fontSize: 13.5, fontWeight: '800', color: colors.ink },
  titleDismissed: { flex: 1, fontSize: 12.5, fontWeight: '600', color: colors.textMuted },
  body: { fontSize: 13, color: colors.text, lineHeight: 18 },
  reason: { fontSize: 11.5, color: colors.textMuted, lineHeight: 15 },
  actions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.sm, flexWrap: 'wrap' },
  dismissedToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: spacing.sm,
    minHeight: 32,
  },
  dismissedToggleText: { fontSize: 12, fontWeight: '700', color: colors.textMuted },
});
