/**
 * Pre-build step: stamps the build date + commit into src/buildInfo.ts so
 * the Settings screen can show exactly which version the site is running —
 * the fastest way to tell whether a deployment actually went out.
 */
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

let commit = process.env.VERCEL_GIT_COMMIT_SHA || '';
if (!commit) {
  try {
    commit = execSync('git rev-parse HEAD', { encoding: 'utf8' }).trim();
  } catch {
    commit = 'unknown';
  }
}

const content = `// Auto-generated by scripts/build-info.js at build time. Do not edit.
export const BUILD_INFO = {
  builtAt: '${new Date().toISOString()}',
  commit: '${commit.slice(0, 7)}',
};
`;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'buildInfo.ts'), content);
console.log(`Build stamp: ${commit.slice(0, 7)} @ ${new Date().toISOString()}`);
